language: node_js
node_js:
  - "10"
addons:
  - chrome: stable
before_script:
  - "npm install"
script:
  - "npm run lint"
  - "npm run test-headless"
  - "npm run e2e"
  - "npm run build"
matrix:
  include:
  - os: linux