language: node_js
node_js:
  - "10.4.1"
sudo: true

addons:
  - chrome: stable

branches:
  only: 
    - master
    - develop

before_script:
  - "npm install -g @angular/cli"

script:
  - "npm run check-translations-sync"
  - "npm run lint"
  - "npm run unit-tests"

matrix:
  include:
  - os: linux